// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDxgyFAL2_9uv422MVBtE-HHd6o5s3g0kQ',
    appId: '1:678011054573:web:00060b60aff95dbc93dfe4',
    messagingSenderId: '678011054573',
    projectId: 'nutrition-app-44301',
    authDomain: 'nutrition-app-44301.firebaseapp.com',
    storageBucket: 'nutrition-app-44301.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDh2bNIWyVxF4XjxwmmkZW4UdNyL2l-uhI',
    appId: '1:678011054573:android:d89dcb0635476c3193dfe4',
    messagingSenderId: '678011054573',
    projectId: 'nutrition-app-44301',
    storageBucket: 'nutrition-app-44301.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC1o_QNVhuSYGDY8b6aZBdwB1DVQiK-CMg',
    appId: '1:678011054573:ios:a0c3cd62748186f093dfe4',
    messagingSenderId: '678011054573',
    projectId: 'nutrition-app-44301',
    storageBucket: 'nutrition-app-44301.firebasestorage.app',
    iosBundleId: 'com.example.nutritionApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC1o_QNVhuSYGDY8b6aZBdwB1DVQiK-CMg',
    appId: '1:678011054573:ios:a0c3cd62748186f093dfe4',
    messagingSenderId: '678011054573',
    projectId: 'nutrition-app-44301',
    storageBucket: 'nutrition-app-44301.firebasestorage.app',
    iosBundleId: 'com.example.nutritionApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDxgyFAL2_9uv422MVBtE-HHd6o5s3g0kQ',
    appId: '1:678011054573:web:62949bcf3c884d0a93dfe4',
    messagingSenderId: '678011054573',
    projectId: 'nutrition-app-44301',
    authDomain: 'nutrition-app-44301.firebaseapp.com',
    storageBucket: 'nutrition-app-44301.firebasestorage.app',
  );
}
